version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file: ".env"
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dbnet

volumes:
  pg_data:

networks:
  dbnet:
    driver: bridge
