FROM mirror.gcr.io/library/python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache -r /app/requirements.txt
# ENV DJANGO_SETTINGS_MODULE=ToDoList_project.settings
COPY api /app/api
COPY ToDoList_project /app/ToDoList_project
COPY manage.py /app/
COPY config.py /app/
COPY entrypoint.sh /app/
CMD ["/app/entrypoint.sh"]

