version: '3.8'

services:
  
  postgres:
    image: postgres:17-alpine
    restart: always
    env_file: ".env"
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dbnet

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - dbnet
    depends_on:
      - "postgres"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - "api"

volumes:
  pg_data:

networks:
  dbnet:
    driver: bridge
  backend:
    driver: bridge
